<?xml version="1.0" encoding="utf-8"?><Database Name="SBSPMS" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.50.4;Initial Catalog=SBSPMS;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SBSPMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BookInfo" Member="BookInfo">
    <Type Name="BookInfo">
      <Column Name="ID" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Press" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>